apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
  labels:
    app: monitoring-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-service
  template:
    metadata:
      labels:
        app: monitoring-service
    spec:
      containers:
      - name: monitoring-service
        image: localhost:5004/monitoring-k8s:latest
        ports:
        - containerPort: 4003
        volumeMounts:
        - name: hostpath-storage
          mountPath: /app/storage
      volumes:
      - name: hostpath-storage
        hostPath:
          path: /Users/stavroslironis/Desktop/storage
          type: Directory
