apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
  labels:
    app: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workers
  template:
    metadata:
      labels:
        app: workers
    spec:
      containers:
      - name: workers
        image: localhost:5004/worker-k8s:latest
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: nfs-storage
          mountPath: /app
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
